### ISSUE TITLE
Historical: integration of new data

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#10]
We need the downloading to occur in two stages. The first downloads everything up until today. The second adds only new data since the last download, without downloading extra data.

**Comment by daveh19** [comment]
@WHops so this one is not yet complete?

**Comment by WHops** [comment]
This is working as well as possible - the DWD keeps changing their old files a lot, so we can't avoid downloading extra data. 
However, it is implemented as nicely as it gets, and the download is fairly quick (~20min on my home internet). 

I'll mark this issue as solved.
