### ISSUE TITLE
Server: data backup!

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#12]
Since the scrapers are still very much works in progress maybe we should have a cron job that backs up the data directories every night. It can just dump into a large backup folder somewhere that can be deleted if it gets too big.

**Comment by erensezener** [comment]
The scrapers don't modify old files. They save new files such that the file name contains the date. So I feel like files are fairly safe.

**Comment by daveh19** [comment]
Good. I figured it was like this. But is there any chance that they can accidentally save under a wrong name? They should really test for file existence before saving. Maybe we can make that an issue under scrapers.

**Comment by daveh19** [comment]
Issue created for scrapers, closing this.
