### ISSUE TITLE
Scrapers: implement file already exists check

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#13]
As discussed [#12](https://github.com/BCCN-Prog/weather_2016/issues/12) scrapers always save to a new file, but they should check that the file does not already exist to avoid overwriting. 

Do they do this?
How do they behave if the file already exists?

**Comment by daveh19** [comment]
@clauslang @akresnia @denisalevi @inesw @ClaudiaWinklmayr @gkBCCN @janfb will write individual versions of this for their own scraper. When all are complete we can close this issue.

**Comment by janfb** [comment]
This could be fixed by including the exact time stamp in the file name, i.e., using time. `time.strftime("%d-%m-%Y_%H_%M_%S")`. This makes every file unique and prevents overwriting.

**Comment by clauslang** [comment]
According to @erensezener, all downloading scripts on the server already create files with exact time stamps.

**Comment by daveh19** [comment]
@clauslang is correct (although I don't know the actual implementation).

But my point in creating the issue is that assuming that this works is not good enough. When writing a file you should always test to see if it exists and have a way of recovering if it does, preferably by appending a unique counter value to the timestamp in the filename.

A simple scenario is if the scraper runs twice in close succession. An alternative is if the clock on the server screws up, but that might be more serious on other grounds.

**Comment by janfb** [comment]
I implemented a function that takes the filename, checks for existence and return a new filename. if the file does not exist, that is just the same name. If it does exist, it looks for a counter at the very end, i.e., `"..._daily_01.html"`, and increments this counter. If there is no counter, it appends a new counter. 
Thus, if I happen to download data for the same date and city 4 times within a second (the time stamp contains seconds), this will result in filenames: `"..._daily.html"`, `"..._daily_01.html"`, `"..._daily_02.html"` and `"..._daily_03.html"`

**Comment by janfb** [comment]
I think you could copy the function, it is independent of the provider, just takes the folder and the filename as an argument and expects `_daily.html` or `_hourly.html` at the end of the filename.
