### ISSUE TITLE
Data Representation Engine: saving of database

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#15]
Database format finalised. Saves to a file or files on disk.

**Comment by daveh19** [comment]
So is this issue dead or alive? @ge00rg @gkBCCN

**Comment by clauslang** [comment]
This will be finished as soon as #14 and #21 are finished

**Comment by daveh19** [comment]
From a file safety point-of-view the issue raised by @erensezener is safe. H5py apparently handles all file access safely and closes files itself on exit https://groups.google.com/d/msg/h5py/hsS1YiMkosk/qY9bVUzpRTIJ
