### ISSUE TITLE
Data Representation Engine: basic API (first implementation)

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#16]
We need to provide ability to do some very basic queries to get data out of the database. This functionality should be provided by providing an API (functions which can be called) which can then be accessed by the query engine.

**Comment by clauslang** [comment]
I think we can call this done, @ge00rg?

**Comment by daveh19** [comment]
I agree, @ge00rg ?

**Comment by clauslang** [comment]
He agrees :)
