### ISSUE TITLE
Accuweather gave HTTP Error 503

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#18]
This happened today for the first time. No other error log.

**Comment by daveh19** [comment]
Too many requests? My recollection is that this script was the one with a lot of requests. If so, it's time to build in some pauses I think. (That or it is another issue with a changing web address.)

**Comment by denisalevi** [comment]
Are you logging the stdout (thats where print() message go, right?). I have print messages telling which of the 500 html request are being processed at a certain time. Would be interesting to see, when the error occurred. If you don't, I can use the logger you are using?
And did the error keep occurring in the last days?

**Comment by erensezener** [comment]
> And did the error keep occurring in the last days?

No

> Are you logging the stdout (thats where print() message go, right?). I have print messages telling which of the 500 html request are being processed at a certain time. Would be interesting to see, when the error occurred.

Since the prints were cluttering things, I removed them. But the downloaded ones are below. So you can see where it happened.

I can add back the prints but I guess it would be better to have a system to save the failed requests and then make them again the same day.


./accuweather_12-05-2016_18:56_cologne_daily_d4_1463072194.html
./accuweather_12-05-2016_18:56_dortmund_daily_d16_1463072194.html
./accuweather_12-05-2016_18:56_rostock_daily_d1_1463072194.html
./accuweather_12-05-2016_18:56_erfurt_daily_d50_1463072194.html
./accuweather_12-05-2016_18:56_bielefeld_hourly_h34_1463072194.html
./accuweather_12-05-2016_18:56_nuremberg_daily_d13_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_hourly_h34_1463072194.html
./accuweather_12-05-2016_18:56_saarbrucken_daily_d7_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_daily_d6_1463072194.html
./accuweather_12-05-2016_18:56_cologne_daily_d15_1463072194.html
./accuweather_12-05-2016_18:56_stuttgart_daily_d15_1463072194.html
./accuweather_12-05-2016_18:56_magdeburg_daily_d90_1463072194.html
./accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d6_1463072194.html
./accuweather_12-05-2016_18:56_hanover_daily_d16_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_daily_d7_1463072194.html
./accuweather_12-05-2016_18:56_berlin_daily_d7_1463072194.html
./accuweather_12-05-2016_18:56_saarbrucken_hourly_h34_1463072194.html
./accuweather_12-05-2016_18:56_stuttgart_daily_d11_1463072194.html
./accuweather_12-05-2016_18:56_nuremberg_hourly_h42_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_daily_d5_1463072194.html
./accuweather_12-05-2016_18:56_dortmund_daily_d11_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_daily_d1_1463072194.html
./accuweather_12-05-2016_18:56_kassel_daily_d6_1463072194.html
./accuweather_12-05-2016_18:56_frankfurt_daily_d17_1463072194.html
./accuweather_12-05-2016_18:56_bremen_daily_d8_1463072194.html
./accuweather_12-05-2016_18:56_hanover_daily_d17_1463072194.html
./accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d90_1463072194.html
./accuweather_12-05-2016_18:56_cologne_hourly_h18_1463072194.html
./accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d3_1463072194.html
./accuweather_12-05-2016_18:56_saarbrucken_daily_d5_1463072194.html
./accuweather_12-05-2016_18:56_hamburg_daily_d4_1463072194.html
./accuweather_12-05-2016_18:56_berlin_daily_d4_1463072194.html
./accuweather_12-05-2016_18:56_frankfurt_daily_d12_1463072194.html
./accuweather_12-05-2016_18:56_leipzig_daily_d30_1463072194.html
./accuweather_12-05-2016_18:56_erfurt_hourly_h18_1463072194.html
./accuweather_12-05-2016_18:56_nuremberg_daily_d2_1463072194.html
./accuweather_12-05-2016_18:56_erfurt_daily_d30_1463072194.html
./accuweather_12-05-2016_18:56_bremen_hourly_h26_1463072194.html
./accuweather_12-05-2016_18:56_erfurt_daily_d14_1463072194.html
./accuweather_12-05-2016_18:56_stuttgart_daily_d14_1463072194.html
./accuweather_12-05-2016_18:56_dortmund_hourly_h18_1463072194.html
./accuweather_12-05-2016_18:56_berlin_daily_d11_1463072194.html
./accuweather_12-05-2016_18:56_munich_daily_d3_1463072194.html
./accuweather_12-05-2016_18:56_berlin_hourly_h34_1463072194.html
./accuweather_12-05-2016_18:56_frankfurt_daily_d7_1463072194.html
./accuweather_12-05-2016_18:56_bielefeld_daily_d2_1463072194.html
./accuweather_12-05-2016_18:56_hanover_hourly_h26_1463072194.html
./accuweather_12-05-2016_18:56_bremen_daily_d12_1463072194.html
./accuweather_12-05-2016_18:56_munich_daily_d1_1463072194.html
./accuweather_12-05-2016_18:56_cologne_daily_d90_1463072194.html
./accuweather_12-05-2016_18:56_stuttgart_daily_d1_1463072194.html
./accuweather_12-05-2016_18:56_berlin_daily_d17_1463072194.html
./accuweather_12-05-2016_18:56_leipzig_daily_d12_1463072194.html
./accuweather_12-05-2016_18:56_frankfurt_daily_d16_1463072194.html
./accuweather_12-05-2016_18:56_bielefeld_daily_d11_1463072194.html
./accuweather_12-05-2016_18:56_magdeburg_daily_d10_1463072194.html
./accuweather_12-05-2016_18:56_dortmund_daily_d70_1463072194.html

**Comment by erensezener** [comment]
here are the times actually in ms accuracy

-rw-rw-r--. 1 pcp2016 pcp2016 100862 2016-05-12 18:57:20.686615677 +0200 accuweather_12-05-2016_18:56_berlin_daily_d11_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99942 2016-05-12 18:57:31.184619887 +0200 accuweather_12-05-2016_18:56_berlin_daily_d17_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100764 2016-05-12 18:57:09.751611292 +0200 accuweather_12-05-2016_18:56_berlin_daily_d4_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100912 2016-05-12 18:56:54.122605009 +0200 accuweather_12-05-2016_18:56_berlin_daily_d7_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 115373 2016-05-12 18:57:23.399616766 +0200 accuweather_12-05-2016_18:56_berlin_hourly_h34_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99501 2016-05-12 18:57:33.700620897 +0200 accuweather_12-05-2016_18:56_bielefeld_daily_d11_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99418 2016-05-12 18:57:25.771617717 +0200 accuweather_12-05-2016_18:56_bielefeld_daily_d2_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 113948 2016-05-12 18:56:41.286599845 +0200 accuweather_12-05-2016_18:56_bielefeld_hourly_h34_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100385 2016-05-12 18:57:27.140618267 +0200 accuweather_12-05-2016_18:56_bremen_daily_d12_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100411 2016-05-12 18:57:03.068608605 +0200 accuweather_12-05-2016_18:56_bremen_daily_d8_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114974 2016-05-12 18:57:16.034613813 +0200 accuweather_12-05-2016_18:56_bremen_hourly_h26_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99351 2016-05-12 18:56:47.361602289 +0200 accuweather_12-05-2016_18:56_cologne_daily_d15_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99146 2016-05-12 18:56:36.110597761 +0200 accuweather_12-05-2016_18:56_cologne_daily_d4_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98139 2016-05-12 18:57:28.801618931 +0200 accuweather_12-05-2016_18:56_cologne_daily_d90_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114064 2016-05-12 18:57:07.200610266 +0200 accuweather_12-05-2016_18:56_cologne_hourly_h18_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99570 2016-05-12 18:56:58.928606942 +0200 accuweather_12-05-2016_18:56_dortmund_daily_d11_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98568 2016-05-12 18:56:37.191598196 +0200 accuweather_12-05-2016_18:56_dortmund_daily_d16_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98610 2016-05-12 18:57:35.293621535 +0200 accuweather_12-05-2016_18:56_dortmund_daily_d70_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114282 2016-05-12 18:57:20.036615416 +0200 accuweather_12-05-2016_18:56_dortmund_hourly_h18_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99385 2016-05-12 18:57:17.551614418 +0200 accuweather_12-05-2016_18:56_erfurt_daily_d14_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98536 2016-05-12 18:57:15.352613537 +0200 accuweather_12-05-2016_18:56_erfurt_daily_d30_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98477 2016-05-12 18:56:39.852599267 +0200 accuweather_12-05-2016_18:56_erfurt_daily_d50_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114301 2016-05-12 18:57:13.827612926 +0200 accuweather_12-05-2016_18:56_erfurt_hourly_h18_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99796 2016-05-12 18:57:11.297611907 +0200 accuweather_12-05-2016_18:56_frankfurt_daily_d12_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99135 2016-05-12 18:57:33.055620637 +0200 accuweather_12-05-2016_18:56_frankfurt_daily_d16_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98980 2016-05-12 18:57:01.684608047 +0200 accuweather_12-05-2016_18:56_frankfurt_daily_d17_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99856 2016-05-12 18:57:24.569617233 +0200 accuweather_12-05-2016_18:56_frankfurt_daily_d7_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100445 2016-05-12 18:57:07.837610521 +0200 accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d3_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100470 2016-05-12 18:56:50.793603669 +0200 accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d6_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99092 2016-05-12 18:57:05.576609612 +0200 accuweather_12-05-2016_18:56_freiburg-im-breisgau_daily_d90_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99605 2016-05-12 18:57:00.105607414 +0200 accuweather_12-05-2016_18:56_hamburg_daily_d1_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99464 2016-05-12 18:57:09.088611024 +0200 accuweather_12-05-2016_18:56_hamburg_daily_d4_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99394 2016-05-12 18:56:57.977606559 +0200 accuweather_12-05-2016_18:56_hamburg_daily_d5_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99486 2016-05-12 18:56:46.674602015 +0200 accuweather_12-05-2016_18:56_hamburg_daily_d6_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99508 2016-05-12 18:56:53.130604612 +0200 accuweather_12-05-2016_18:56_hamburg_daily_d7_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 113591 2016-05-12 18:56:44.271601048 +0200 accuweather_12-05-2016_18:56_hamburg_hourly_h34_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99156 2016-05-12 18:56:51.944604132 +0200 accuweather_12-05-2016_18:56_hanover_daily_d16_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99126 2016-05-12 18:57:04.326609108 +0200 accuweather_12-05-2016_18:56_hanover_daily_d17_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114545 2016-05-12 18:57:26.494618009 +0200 accuweather_12-05-2016_18:56_hanover_hourly_h26_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99554 2016-05-12 18:57:00.882607726 +0200 accuweather_12-05-2016_18:56_kassel_daily_d6_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99732 2016-05-12 18:57:32.405620377 +0200 accuweather_12-05-2016_18:56_leipzig_daily_d12_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  98860 2016-05-12 18:57:12.603612434 +0200 accuweather_12-05-2016_18:56_leipzig_daily_d30_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 101025 2016-05-12 18:57:34.513621221 +0200 accuweather_12-05-2016_18:56_magdeburg_daily_d10_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99837 2016-05-12 18:56:49.458603133 +0200 accuweather_12-05-2016_18:56_magdeburg_daily_d90_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99574 2016-05-12 18:57:28.097618650 +0200 accuweather_12-05-2016_18:56_munich_daily_d1_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99153 2016-05-12 18:57:21.759616107 +0200 accuweather_12-05-2016_18:56_munich_daily_d3_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100102 2016-05-12 18:56:42.613600379 +0200 accuweather_12-05-2016_18:56_nuremberg_daily_d13_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99931 2016-05-12 18:57:14.565613222 +0200 accuweather_12-05-2016_18:56_nuremberg_daily_d2_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114449 2016-05-12 18:56:56.808606088 +0200 accuweather_12-05-2016_18:56_nuremberg_hourly_h42_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99980 2016-05-12 18:56:38.065598550 +0200 accuweather_12-05-2016_18:56_rostock_daily_d1_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99789 2016-05-12 18:57:08.466610774 +0200 accuweather_12-05-2016_18:56_saarbrucken_daily_d5_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99788 2016-05-12 18:56:45.136601397 +0200 accuweather_12-05-2016_18:56_saarbrucken_daily_d7_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 114301 2016-05-12 18:56:55.355605504 +0200 accuweather_12-05-2016_18:56_saarbrucken_hourly_h34_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100051 2016-05-12 18:56:56.049605782 +0200 accuweather_12-05-2016_18:56_stuttgart_daily_d11_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016 100300 2016-05-12 18:57:29.988619411 +0200 accuweather_12-05-2016_18:56_stuttgart_daily_d1_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99969 2016-05-12 18:57:18.747614902 +0200 accuweather_12-05-2016_18:56_stuttgart_daily_d14_1463072194.html
-rw-rw-r--. 1 pcp2016 pcp2016  99984 2016-05-12 18:56:48.682602820 +0200 accuweather_12-05-2016_18:56_stuttgart_daily_d15_1463072194.html

**Comment by denisalevi** [comment]
Ok. So it is downloading and working fine right now? So I only try to catch a possible http error and if so, just let it sleep for a few seconds? or an hour?

**Comment by erensezener** [comment]
That's probably a bad idea since it will block other scripts. In worst case for 500 hours. A few secs probably won't fix the problem as well. 

If you can call your script asynchronously from the main script, it would work though.

**Comment by denisalevi** [comment]
Since the error didn't reappear, I will focus on more urgent stuff for now. If it reappears, I can look into it.
