### ISSUE TITLE
Couldn't download data on 11.05

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#19]
We couldn't download any data on 11.05 since I forgot to comment out a line on Tuesday when I was adding the logger. I fixed it now. 10.05 and 12.05 is fine. Sorry :/

On a positive note, the logger works fine though.

**Comment by erensezener** [comment]
This is no longer an issue so I will close it after enough people shame me :P

**Comment by daveh19** [comment]
Does the emailing of the logs work or did you give up on that?

**Comment by erensezener** [comment]
I didn't have time to do it last week. But I log in every 2-3 days these days so I would catch a problem before it is too late.
