### ISSUE TITLE
update wetter_de download script...

### ISSUE THREAD

**Issue by gkBCCN** [BCCN-Prog/weather_2016#20]
...and move all HTML in current download location into a subdirectory called "new/".

**Comment by erensezener** [comment]
All wetter_de downloads or all the download?

**Comment by gkBCCN** [comment]
The updated script saves htmls into "new/", but the old didn't.  Can you move the htmls downloaded by the old script into "new/", and update the script? Thanks. @erensezener

**Comment by erensezener** [comment]
What do you mean by update the script? You mean pull from the remote?

**Comment by erensezener** [comment]
Pulled it and changed the save directory in the main script.
