### ISSUE TITLE
Data Representation Engine: historical data

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#21]
Who is responsible for integrating historical data into the data base? Is it the data base side or the historical data side?
@WHops @ge00rg @gkBCCN

**Comment by daveh19** [comment]
Still need an answer on this one. It's important that you don't find that you left a gap that neither side worked on.

**Comment by clauslang** [comment]
@WHops and @ge00rg did this last week. Now debugging, because it doesn't work as expected.

**Comment by clauslang** [comment]
Bug fixed by @ge00rg
