### ISSUE TITLE
Visualisation: get Basemap API working for some test data

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#22]
This is becoming urgent. The Basemap API is perfect for plotting data but the guys are having trouble with Python formatting for the API calls.

**Comment by daveh19** [comment]
http://basemaptutorial.readthedocs.io/en/latest/plotting_data.html

**Comment by daveh19** [comment]
http://basemaptutorial.readthedocs.io/en/latest/plotting_data.html#contourf

**Comment by daveh19** [comment]
conda install basemap
is a requirement.

**Comment by daveh19** [comment]
https://github.com/BCCN-Prog/weather_2016/blob/master/map/map.py the relevant code

**Comment by clauslang** [comment]
Thanks for the links, will look into it until next time

**Comment by daveh19** [comment]
weather_2016/map/map.py is the file @MaxKirstein and @filipvercruysse were working on. It works apart from having the data in the correct format for map.contourf()

**Comment by daveh19** [comment]
Try to get (fake) temperature values plotted on the city locations which we will be using for most of the project. Overlaying a colourmap with non-evenly spaced locations will be quite difficult and will be the follow-up step.

**Comment by denisalevi** [comment]
An example plot with randomly generated temperature data can be with:
```
python path/to/weather_2016/map/map_mvp.py
```
Need `basemap` installed.

**Comment by denisalevi** [comment]
How to use the map function:

```python
    from map import station_map
    coordinates = # array of [latitude, longitude] entries (shape = (num_cities, 2))
    values = # array of size = num_cites
    station_map(coordinates, values, hex_grid_size=(50,50))
```

You need to adapt the hex_grid_size to the number of cities you have. hex_grid_size is the number of hexagons to fit in the picture, NOT the size of the hexagon.

**Comment by clauslang** [comment]
map() is a built-in python function, which is probably the reason why the import does not work for me.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "//anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "/Users/clauslang/Desktop/BCCN/weather_2016_new/query_engine/command_line_interface.py", line 2, in <module>
    from map import station_map
ImportError: cannot import name 'station_map'`
