### ISSUE TITLE
Query Engine: first attempt 

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#24]
The query engine is the program executable. It provides a prompt at which a query is entered. It then translates this query into an API call on the Data Representation Engine. It then takes the response and formats it and outputs it (potentially calling a Visualisation or Report Engine to pretify the output).

**Comment by daveh19** [comment]
@clauslang was this solved by your recent commit? https://github.com/BCCN-Prog/weather_2016/commit/11b2d46256188743d7a003fa492356cd26e9a723  Congrats by the way!

**Comment by clauslang** [comment]
Wouldn't call it solved before finalization of MVP, first commit was very rudimentary and limited, also hacky code.
