### ISSUE TITLE
Reports: first attempt 

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#25]
This will be the second phase of the project/product. The Query Engine will pass output to a Report Engine, which will place it in an attractive format in a PDF document. 

In subsequent versions the Report Engine should generate its own queries for fancier reports.

**Comment by clauslang** [comment]
If we are going to create pdfs directly, we should use [reportlab](https://pypi.python.org/pypi/reportlab).

Alternatively, as @erensezener suggested, we could generate html files, (e.g. with [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/), with which everyone from the former scraping group is now familiar with) which could also be printed as pdfs if need be.

**Comment by clauslang** [comment]
There is not enough time to implement a report engine that would generate reports automatically.
