### ISSUE TITLE
Scraping: extending file existence checking to all scrapers

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#27]
As @janfb solved in #13 the other scrapers need to add file exists checking before saving their downloaded files.

@ClaudiaWinklmayr @clauslang @inesw @akresnia 

Use the file_existence_check() function defined in this commit: https://github.com/BCCN-Prog/weather_2016/commit/8aa3fc63ce7e9781544235d559f5dd84ec958b12#diff-160c108f701e3f1d045e857ab140a408

**Comment by janfb** [comment]
I can help to integrate the function I wrote in everyone's script. But I think we don't need it because the time stamp in the file name has second precision. We will overwrite only if we save twice within a second.

**Comment by janfb** [comment]
We close it since the time stamp is in seconds.
