### ISSUE TITLE
Visualisation: plotting of colourmap where the cities are not on an evenly spaced grid

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#29]
This is going to be quite difficult, since you will only have data points for 20 locations in Germany. It probably requires a 'growth' algorithm where data points reach out until the meet one another. Should be tackled immediately once the manpower is free from getting the MVP up and running.

**Comment by denisalevi** [comment]
So far the hexgrid option we are using does connect the datapoints, taking the mean if within one hexagonal palett there are multiple datapoints. Since the 20 sities are chosen more or less evenly spaced, we might find a right gridsize, that results in one pallet per city. But of course there is no pretty change of colors btwn paletts.

**Comment by daveh19** [comment]
Excellent. It still might need a bit of a home grown growth algorithm to expand each colour region out from its city of origin until it meets its nearest neighbour, or alternatively an interpolation version. But we can discuss next week. We'll close this issue after we have a good working example.

**Comment by denisalevi** [comment]
`matplotlib.mlab` has a `griddata` function, that creates a grid between unevenly spaced datapoints. Interpolation methods are `linear` or `nn`, where the latter is a "natural neighbour interpolation method". This makes a home grown growth algorithm unnecessary. 
To use the `nn` method, you need to install the [Natgrid](http://www.ncarg.ucar.edu//ngmath/natgrid/nnhome.html) package. To do so with `conda`, type:
```
conda install --channel https://conda.anaconda.org/jochym natgrid
```
Integrating this into the plotting functions is in progress.

**Comment by daveh19** [comment]
I've added instructions for MacOS users to Requirements.txt on how to install this dependency. The source code is now a submodule of the project so that we don't have to worry about it changing.
