### ISSUE TITLE
Scraping: extending the test_scraper_output.py from #11 to all scrapers

### ISSUE THREAD

**Issue by janfb** [BCCN-Prog/weather_2016#31]
@ClaudiaWinklmayr @clauslang @inesw @akresnia @denisalevi we need to sit down and adapt this testing script for your cases.

**Comment by clauslang** [comment]
Done for all scripts except wunderground, @inesw @janfb

**Comment by janfb** [comment]
Who is working an wunderground?

**Comment by clauslang** [comment]
@inesw

**Comment by clauslang** [comment]
Done for wunderground
