### ISSUE TITLE
Change site name value in dictionary to integers 

### ISSUE THREAD

**Issue by gkBCCN** [BCCN-Prog/weather_2016#34]
integers for each site are on Wiki/Main project resources under the Data Sources heading.

@clauslang @ClaudiaWinklmayr @inesw @denisalevi @janfb

**Comment by daveh19** [comment]
Query: you guys seem to be changing your dictionary encodings in a few ways today, is this 'backward compatible' for integration of scrapes into the database? ie. whatever the current workflow is, will it hiccup on old versus new scrapes or does it all work seamlessly?

**Comment by clauslang** [comment]
Since there is no scraping database yet and this is only a change in a detail of how the data extraction scripts communicate with the database, we will be fine.
(In other words: This is the only workflow version, and it will be applied from next time on.)

**Comment by clauslang** [comment]
@inesw, I assigned number 5 to wunderground (so that 'historical' now has ID 6). I will quickly update your code.

**Comment by clauslang** [comment]
Done, this was the last script that hadn't implemented that yet, so closing this.
