### ISSUE TITLE
Register for the course!!!

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#38]
Those of you in the BCCN masters course really need to register for the course! Robert Martin has only received two registrations so far.

@erensezener @akresnia @clauslang @denisalevi @ge00rg @inesw @janfb @rahul-nt @WHops @gkBCCN
Please tell anyone I've missed tagging.

This is a breaking bug for the system, without fixing it you get no credits!

**Comment by clauslang** [comment]
Whose registration has he received already?

**Comment by daveh19** [comment]
I thought that you were supposed to personally hand it to him. I have no idea.

**Comment by daveh19** [comment]
He has yours and @janfb 's @clauslang

**Comment by daveh19** [comment]
I'm assuming this is done by now. Otherwise, see you next year!
