### ISSUE TITLE
Visualisation: generate basic map of Germany only once

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#41]
Map generation is slow, whereas everything else is fast. We can generate a single Basemap in memory with Germany and any other _permanent_ information plotted on it. This can then be stored as an object in memory which any figures produced can then just copy and plot data on top of. (Obviously this won't work if we need some of the basemap data to be visible on top of the data, but it should work for the outline of Germany at least)

**Comment by clauslang** [comment]
Did you end up implementing this, @denisalevi ?

**Comment by denisalevi** [comment]
i haven't, no, @MaxKirstein @akresnia did any of you look into it?

**Comment by clauslang** [comment]
We have no resources for this
