### ISSUE TITLE
Query engine: expanding the repertoire of basic queries

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#43]
Define a basic set of queries that we want our query engine to handle.

**Comment by rahul-nt** [comment]
The file with the query has been committed to the repo:
Commit number:
baad7d0e9b9f86d8034aff42a4131600b8e004ae

**Comment by clauslang** [comment]
@inesw will create a wiki document where everyone can brainstorm and share their ideas about what queries we should support

**Comment by clauslang** [comment]
Can't believe I can assign only 10 people at the most :D Also assigned: @MaxKirstein

**Comment by clauslang** [comment]
@inesw and me defined a set of queries that we are going to present and discuss in a minute.
