### ISSUE TITLE
Do some research about NLP and NLP APIs

### ISSUE THREAD

**Issue by clauslang** [BCCN-Prog/weather_2016#45]
So that we get a better idea what's possible, how it could benefit our product, and how difficult it would be to implement.

**Comment by daveh19** [comment]
Not doing this now (I presume).

**Comment by clauslang** [comment]
I think, @janfb did something on this last time, but maybe we should give this up if we need workforce on other issues.

**Comment by daveh19** [comment]
This has clearly been done by @janfb . Closing issue.
