### ISSUE TITLE
Make sure hourly indices are in line with our convention in scraping scripts

### ISSUE THREAD

**Issue by clauslang** [BCCN-Prog/weather_2016#50]
From #23:

- For predictions for the next day, a new dictionary has to be created and passed to the database side separately, that is, one hourly dictionary contains only the predictions for the date that is specified in the 'date' timestamp. The hourly indices denote the actual time that the prediction is for, e.g. index 19 is the index for the prediction for 7pm.

Please drop a quick line here once this is done for your script so that we have an overview.

**Comment by clauslang** [comment]
Done for owm.

**Comment by akresnia** [comment]
done for timeanddate

**Comment by janfb** [comment]
Done for wetter.com

**Comment by gkBCCN** [comment]
Done for wetter.de

**Comment by inesw** [comment]
done for wunderground

**Comment by denisalevi** [comment]
done for accuweather
