### ISSUE TITLE
Add extra column 'predicition_time' to hourly database and import it properly from the scraping dictionaries

### ISSUE THREAD

**Issue by clauslang** [BCCN-Prog/weather_2016#52]
From #23:
- On the highest hierarchy level of the dictionary, i.e. as neighbour to 'city', 'site', 'date', 'daily', 'hourly', the dictionary has to have another entry 'prediction_time', that denotes the time when the html file was downloaded as an int in the format YYYYMMDDHHMM. This should be easy to implement, since this timestamp is included in the file names.
- **This information then has to be stored in an additional column in the hourly database.**

**Comment by akresnia** [comment]
Today you said this should be integer. Which version is correct?

**Comment by clauslang** [comment]
You're right, it should be int. Sorry about the confusion. I will update this.

**Comment by inesw** [comment]
I did it for wunderground
