### ISSUE TITLE
owm sometimes does logically impossible predictions: what do we do with them?

### ISSUE THREAD

**Issue by clauslang** [BCCN-Prog/weather_2016#57]
Sometimes, for the daily predictions, owm says that the highest temperature is lower than the lowest one, e.g.:

file: owm_06_06_2016_05_18_frankfurt.html
prediction for: June 15th
high: 19.2°C 
low: 19.7°C
(see attached screenshot and file)

For now, we ignore the prediction of that day completely (because Jan's test of the output raises an AssertinError). But I think, we should actually add the values to the DB. 
First, because we shouldn't manipulate the data that we get from the websites.
Second, this is an interesting result if we are analyzing e.g. the prediction accuracy of the different sites.

[owm_06_06_2016_05_18_frankfurt.html.zip](https://github.com/BCCN-Prog/weather_2016/files/325945/owm_06_06_2016_05_18_frankfurt.html.zip)

![2016-06-21 05 25 01 pm](https://cloud.githubusercontent.com/assets/9513701/16235421/1a3fb88a-37d5-11e6-9605-60b5097c58cf.png)

**Comment by daveh19** [comment]
I agree. Save it to the database.

**Comment by clauslang** [comment]
Need to adjust the output tester accordingly then, @janfb

**Comment by janfb** [comment]
I could either just remove this test from testing or make an exception for owm.
