### ISSUE TITLE
Planning: minimum viable product

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#6]
I think that it's time to answer the following question:

What is the smallest possible output which shows that we have correctly,
(i) gathered the data
(ii) encoded the data in a data representation engine
(iii) allow queries of the data
(iv) build a simple report via the amalgamation of queries

**Comment by daveh19** [comment]
By the way, the deadline for actually achieving the milestone of the minimum viable product is then the end of May. There is leeway on this, but basically something should work by then.

**Comment by clauslang** [comment]
Informed everyone of the deadline today. Will define the MVP at the beginning of next session. Homework for everyone until then: Think about what it should look like / what features it should contain.

**Comment by daveh19** [comment]
Excellent. Just remember this is a basic proof that the end-to-end system works so it doesn't need to be fancy or handle multiple queries.

**Comment by daveh19** [comment]
Will be provided with Protocol for today.

**Comment by daveh19** [comment]
Closed with commit [https://github.com/BCCN-Prog/weather_2016/commit/57403518f1b547c18b8fbb34f42f74c3ca31e493](https://github.com/BCCN-Prog/weather_2016/commit/57403518f1b547c18b8fbb34f42f74c3ca31e493)
