### ISSUE TITLE
Scrapers: detection that weather location has not changed

### ISSUE THREAD

**Issue by daveh19** [BCCN-Prog/weather_2016#7]
Each of the scrapers needs a detection mechanism to make sure that the source webpage still contains the information about the desired location (ie. that they haven't changed the web address and substituted it with another forecast).

**Comment by daveh19** [comment]
Specialised versions of this issue should be propagated to all of the individual scrapers. They all contribute to accomplishing the milestone.

**Comment by daveh19** [comment]
@clauslang @akresnia @denisalevi @inesw @ClaudiaWinklmayr @gkBCCN @janfb will write individual versions of this for their own scraper. When all are complete we can close this issue.

**Comment by denisalevi** [comment]
My scraper checks the html title page for the city name and wather its daily or hourly forecast. From my side done.

**Comment by clauslang** [comment]
@inesw @gkBCCN @claus

**Comment by daveh19** [comment]
Did you tag the wrong Claus?

**Comment by clauslang** [comment]
Oh, I meant @clauslang of course 😄

**Comment by janfb** [comment]
Is this done by now?

**Comment by daveh19** [comment]
@gkBCCN @inesw @clauslang can we close this?

**Comment by clauslang** [comment]
Yes, even though not everybody has done this. It's too late now anyways.
