### ISSUE TITLE
Validate owm data

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#85]
Please download the data with _ow suffix here: https://drive.google.com/folderview?id=0BwQc_CC3arWWMTNYaEpCOHlKZmc&usp=sharing

And look at nanmax(), unique() etc of columns and the number of entries to see if it makes sense.

**Comment by erensezener** [comment]
It works like this:

``` python
import h5py
import numpy as np

>>> h5 = h5py.File('hourly_database.hdf5', 'r'); data = h5['weather_data'][:]
>>> np.unique(data[:,2])
array([  0.00000000e+00,   1.00000000e+00,   4.00000000e+00,
         2.01606212e+11])
```

Beware that the data is padded with rows of zero from the bottom.

**Comment by clauslang** [comment]
Looks good.
