### ISSUE TITLE
Timeanddate does not create a DB

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#86]
For some reason, timeanddate did not create a database. Contact me with the possible meeting times to look at the code or I can give you access to the server with a script that only calls your scraper.

I couldn't find Alicja's username. So can someone assign the issue to her?

**Comment by akresnia** [comment]
My username is akresnia, but you don't need to assign me as I've read the
message :)
14 lip 2016 09:49 "C. Eren Sezener" <notifications@github.com> napisał(a):

**Comment by erensezener** [comment]
Fixed
